# build stage
FROM threetee/golang-alpine-dep:1.14.6 AS build-env

ADD . /go/src/github.com/threetee/http3go1/

RUN \
  cd /go/src/github.com/threetee/http3go1 && \
  make redirector

# final stage
FROM alpine
WORKDIR /app
COPY --from=build-env /go/src/github.com/threetee/http3go1/redirector /app/

ENV REDIRECTOR_PORT=9000

EXPOSE 9000

CMD ["/app/redirector", "--logtostderr=true"]

