# build stage
FROM threetee/golang-alpine-dep AS build-env
ADD . /go/src/github.com/threetee/http3go1/
RUN cd /go/src/github.com/threetee/http3go1 && dep ensure && go build -o redirector redirector.go

# final stage
FROM alpine
WORKDIR /app
COPY --from=build-env /go/src/github.com/threetee/http3go1/redirector /app/

ENV REDIRECTOR_PORT=9000

EXPOSE 9000

CMD ./redirector --logtostderr=true

