# build stage
FROM threetee/golang-alpine-dep:1.14.6 AS build-env
ADD . /go/src/github.com/threetee/http3go1/
RUN \
  cd /go/src/github.com/threetee/http3go1 && \
  make admin && \
  tar cvzpf /tmp/build.tar.gz admin web/static/

# final stage
FROM alpine
WORKDIR /app
COPY --from=build-env /tmp/build.tar.gz /tmp/
RUN tar xvzpf /tmp/build.tar.gz

ENV ADMIN_PORT=9000
ENV ADMIN_STATICDIR=/app/web/static

EXPOSE 9001

CMD ["/app/admin", "--logtostderr=true"]

